"""
RAG-based Clinical Assistant for MedAdapt-SAM
Integrates medical knowledge retrieval with segmented findings.
"""

from typing import List, Dict, Any
import numpy as np

class MedAssistantRAG:
    """Medical Assistant with Retrieval-Augmented Generation capabilities"""
    
    def __init__(self):
        # Simulated medical knowledge base for Brain Tumors (BraTS context)
        self.knowledge_base = [
            {
                "topic": "GBM (Glioblastoma)",
                "content": "Glioblastoma Multiforme typically shows high enhancing tumor (ET) regions on T1CE and extensive edema (WT) on FLAIR.",
                "keywords": ["enhancing", "ET", "high-grade", "active"]
            },
            {
                "topic": "Low Grade Glioma",
                "content": "LGG often presents with high Whole Tumor (WT) volume but low or absent Enhancing Tumor (ET) component.",
                "keywords": ["low enhancement", "WT", "slow-growing"]
            },
            {
                "topic": "Tumor Core",
                "content": "The Tumor Core (TC) includes the necrotic and non-enhancing tumor regions along with the enhancing component.",
                "keywords": ["core", "TC", "necrotic"]
            }
        ]
        
    def retrieve_context(self, query: str) -> str:
        """Simple keyword-based retrieval for the demo RAG"""
        query = query.lower()
        results = []
        for entry in self.knowledge_base:
            if any(keyword.lower() in query for keyword in entry['keywords']):
                results.append(entry['content'])
        
        return " ".join(results) if results else "Consult a neuro-oncology specialist for this specific finding."

    def ask(self, query: str, context_stats: Dict[str, Any] = None) -> str:
        """Generate a response based on query and segmentation context"""
        retrieved_med_info = self.retrieve_context(query)
        
        if context_stats:
            stats_str = f"Current Case Info: WT Vol: {context_stats.get('WT', 0)}, ET/TC ratio: {context_stats.get('ET_TC_ratio', 0):.2f}."
        else:
            stats_str = "No specific scan data provided."
            
        # Simulated LLM response generation
        response = f"AI Medical Assistant: {retrieved_med_info}\n\n{stats_str}\n\nIs there anything else you want to know about these MRI findings?"
        return response

def get_diagnostic_report(patient_id: str, masks: Dict[str, np.ndarray]) -> str:
    """Generates a detailed clinical report template"""
    volumes = {k: int(np.sum(v > 0.5)) for k, v in masks.items()}
    
    et = volumes.get('ET', 0)
    tc = volumes.get('TC', 0)
    wt = volumes.get('WT', 0)
    
    classification = "Suspicious for High Grade" if et > 5000 else "Consistent with Low Grade"
    
    report = f"""
    🏥 CLINICAL MRI SEGMENTATION REPORT
    -------------------------------------------
    Patient ID: {patient_id}
    Case Status: {classification}
    
    VOLUMETRIC ANALYSIS:
    - Whole Tumor (WT): {wt:,} px
    - Tumor Core (TC): {tc:,} px
    - Enhancing Tumor (ET): {et:,} px
    
    OBSERVATIONS:
    The enhancing component (ET) constitutes {(et/tc*100 if tc>0 else 0):.1f}% of the tumor core.
    Extensive peritumoral edema is observed in the FLAIR/WT volume.
    
    INTERPRETATION:
    Findings suggest {classification.lower()} glioma. Please correlate with clinical 
    symptoms and biopsy results for definitive diagnosis.
    -------------------------------------------
    (Generated by MedAdapt-SAM AI Engine)
    """
    return report
